version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
      timezone: 'Europe/Zurich'
    open-pull-requests-limit: 10
    target-branch: 'develop'
    labels:
      - 'dependencies'
      - 'npm'
    reviewers:
      - 'SolombrinoIsmail'
    assignees:
      - 'SolombrinoIsmail'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    allow:
      - dependency-type: 'all'
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: 'next'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
    groups:
      # Group all non-major updates together
      non-major:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      # Group all ESLint related packages
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
      # Group all testing related packages
      testing:
        patterns:
          - '@testing-library/*'
          - 'vitest*'
          - '@vitest/*'
          - 'playwright*'
          - '@playwright/*'
      # Group all Radix UI packages
      radix-ui:
        patterns:
          - '@radix-ui/*'
      # Group all type definition packages
      types:
        patterns:
          - '@types/*'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
      timezone: 'Europe/Zurich'
    open-pull-requests-limit: 5
    target-branch: 'develop'
    labels:
      - 'dependencies'
      - 'github-actions'
    reviewers:
      - 'SolombrinoIsmail'
    assignees:
      - 'SolombrinoIsmail'
    commit-message:
      prefix: 'ci'
      include: 'scope'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
      timezone: 'Europe/Zurich'
    open-pull-requests-limit: 5
    target-branch: 'develop'
    labels:
      - 'dependencies'
      - 'docker'
    reviewers:
      - 'SolombrinoIsmail'
    assignees:
      - 'SolombrinoIsmail'
    commit-message:
      prefix: 'build'
      include: 'scope'
