/**
 * Swiss market localization constants and utilities
 * Supports German (Switzerland), French (Switzerland), Italian (Switzerland), and Romansh
 */

// Language configurations
export const SUPPORTED_LOCALES = [
  {
    code: 'de-CH',
    name: 'Deutsch (Schweiz)',
    nativeName: 'Deutsch',
    flag: '🇨🇭',
    direction: 'ltr' as const,
  },
  {
    code: 'fr-CH',
    name: 'Français (Suisse)',
    nativeName: 'Français',
    flag: '🇨🇭',
    direction: 'ltr' as const,
  },
  {
    code: 'it-CH',
    name: 'Italiano (Svizzera)',
    nativeName: 'Italiano',
    flag: '🇨🇭',
    direction: 'ltr' as const,
  },
  {
    code: 'rm-CH',
    name: 'Rumantsch',
    nativeName: 'Rumantsch',
    flag: '🇨🇭',
    direction: 'ltr' as const,
  },
] as const;

export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number]['code'];

// Swiss cantons with translations
export const SWISS_CANTONS = {
  'de-CH': [
    { code: 'AG', name: 'Aargau' },
    { code: 'AI', name: 'Appenzell Innerrhoden' },
    { code: 'AR', name: 'Appenzell Ausserrhoden' },
    { code: 'BE', name: 'Bern' },
    { code: 'BL', name: 'Basel-Landschaft' },
    { code: 'BS', name: 'Basel-Stadt' },
    { code: 'FR', name: 'Freiburg' },
    { code: 'GE', name: 'Genf' },
    { code: 'GL', name: 'Glarus' },
    { code: 'GR', name: 'Graubünden' },
    { code: 'JU', name: 'Jura' },
    { code: 'LU', name: 'Luzern' },
    { code: 'NE', name: 'Neuenburg' },
    { code: 'NW', name: 'Nidwalden' },
    { code: 'OW', name: 'Obwalden' },
    { code: 'SG', name: 'St. Gallen' },
    { code: 'SH', name: 'Schaffhausen' },
    { code: 'SO', name: 'Solothurn' },
    { code: 'SZ', name: 'Schwyz' },
    { code: 'TG', name: 'Thurgau' },
    { code: 'TI', name: 'Tessin' },
    { code: 'UR', name: 'Uri' },
    { code: 'VD', name: 'Waadt' },
    { code: 'VS', name: 'Wallis' },
    { code: 'ZG', name: 'Zug' },
    { code: 'ZH', name: 'Zürich' },
  ],
  'fr-CH': [
    { code: 'AG', name: 'Argovie' },
    { code: 'AI', name: 'Appenzell Rhodes-Intérieures' },
    { code: 'AR', name: 'Appenzell Rhodes-Extérieures' },
    { code: 'BE', name: 'Berne' },
    { code: 'BL', name: 'Bâle-Campagne' },
    { code: 'BS', name: 'Bâle-Ville' },
    { code: 'FR', name: 'Fribourg' },
    { code: 'GE', name: 'Genève' },
    { code: 'GL', name: 'Glaris' },
    { code: 'GR', name: 'Grisons' },
    { code: 'JU', name: 'Jura' },
    { code: 'LU', name: 'Lucerne' },
    { code: 'NE', name: 'Neuchâtel' },
    { code: 'NW', name: 'Nidwald' },
    { code: 'OW', name: 'Obwald' },
    { code: 'SG', name: 'Saint-Gall' },
    { code: 'SH', name: 'Schaffhouse' },
    { code: 'SO', name: 'Soleure' },
    { code: 'SZ', name: 'Schwytz' },
    { code: 'TG', name: 'Thurgovie' },
    { code: 'TI', name: 'Tessin' },
    { code: 'UR', name: 'Uri' },
    { code: 'VD', name: 'Vaud' },
    { code: 'VS', name: 'Valais' },
    { code: 'ZG', name: 'Zoug' },
    { code: 'ZH', name: 'Zurich' },
  ],
  'it-CH': [
    { code: 'AG', name: 'Argovia' },
    { code: 'AI', name: 'Appenzello Interno' },
    { code: 'AR', name: 'Appenzello Esterno' },
    { code: 'BE', name: 'Berna' },
    { code: 'BL', name: 'Basilea Campagna' },
    { code: 'BS', name: 'Basilea Città' },
    { code: 'FR', name: 'Friburgo' },
    { code: 'GE', name: 'Ginevra' },
    { code: 'GL', name: 'Glarona' },
    { code: 'GR', name: 'Grigioni' },
    { code: 'JU', name: 'Giura' },
    { code: 'LU', name: 'Lucerna' },
    { code: 'NE', name: 'Neuchâtel' },
    { code: 'NW', name: 'Nidvaldo' },
    { code: 'OW', name: 'Obvaldo' },
    { code: 'SG', name: 'San Gallo' },
    { code: 'SH', name: 'Sciaffusa' },
    { code: 'SO', name: 'Soletta' },
    { code: 'SZ', name: 'Svitto' },
    { code: 'TG', name: 'Turgovia' },
    { code: 'TI', name: 'Ticino' },
    { code: 'UR', name: 'Uri' },
    { code: 'VD', name: 'Vaud' },
    { code: 'VS', name: 'Vallese' },
    { code: 'ZG', name: 'Zugo' },
    { code: 'ZH', name: 'Zurigo' },
  ],
} as const;

// Common UI translations
export const UI_TRANSLATIONS = {
  common: {
    'de-CH': {
      save: 'Speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      close: 'Schliessen',
      back: 'Zurück',
      next: 'Weiter',
      previous: 'Zurück',
      loading: 'Wird geladen...',
      error: 'Fehler',
      success: 'Erfolgreich',
      warning: 'Warnung',
      info: 'Information',
      yes: 'Ja',
      no: 'Nein',
      ok: 'OK',
      search: 'Suchen',
      filter: 'Filter',
      sort: 'Sortieren',
      export: 'Exportieren',
      import: 'Importieren',
      print: 'Drucken',
      download: 'Herunterladen',
      upload: 'Hochladen',
    },
    'fr-CH': {
      save: 'Enregistrer',
      cancel: 'Annuler',
      delete: 'Supprimer',
      edit: 'Modifier',
      close: 'Fermer',
      back: 'Retour',
      next: 'Suivant',
      previous: 'Précédent',
      loading: 'Chargement...',
      error: 'Erreur',
      success: 'Succès',
      warning: 'Avertissement',
      info: 'Information',
      yes: 'Oui',
      no: 'Non',
      ok: 'OK',
      search: 'Rechercher',
      filter: 'Filtrer',
      sort: 'Trier',
      export: 'Exporter',
      import: 'Importer',
      print: 'Imprimer',
      download: 'Télécharger',
      upload: 'Téléverser',
    },
    'it-CH': {
      save: 'Salva',
      cancel: 'Annulla',
      delete: 'Elimina',
      edit: 'Modifica',
      close: 'Chiudi',
      back: 'Indietro',
      next: 'Avanti',
      previous: 'Precedente',
      loading: 'Caricamento...',
      error: 'Errore',
      success: 'Successo',
      warning: 'Avviso',
      info: 'Informazione',
      yes: 'Sì',
      no: 'No',
      ok: 'OK',
      search: 'Cerca',
      filter: 'Filtro',
      sort: 'Ordina',
      export: 'Esporta',
      import: 'Importa',
      print: 'Stampa',
      download: 'Scarica',
      upload: 'Carica',
    },
  },
  forms: {
    'de-CH': {
      required: 'Pflichtfeld',
      optional: 'Optional',
      firstName: 'Vorname',
      lastName: 'Nachname',
      email: 'E-Mail',
      phone: 'Telefon',
      address: 'Adresse',
      street: 'Strasse',
      postalCode: 'Postleitzahl',
      city: 'Ort',
      canton: 'Kanton',
      country: 'Land',
      birthDate: 'Geburtsdatum',
      password: 'Passwort',
      confirmPassword: 'Passwort bestätigen',
      termsAndConditions: 'AGB akzeptieren',
      privacyPolicy: 'Datenschutzerklärung akzeptieren',
    },
    'fr-CH': {
      required: 'Obligatoire',
      optional: 'Optionnel',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'E-mail',
      phone: 'Téléphone',
      address: 'Adresse',
      street: 'Rue',
      postalCode: 'Code postal',
      city: 'Ville',
      canton: 'Canton',
      country: 'Pays',
      birthDate: 'Date de naissance',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      termsAndConditions: 'Accepter les CGV',
      privacyPolicy: 'Accepter la politique de confidentialité',
    },
    'it-CH': {
      required: 'Obbligatorio',
      optional: 'Opzionale',
      firstName: 'Nome',
      lastName: 'Cognome',
      email: 'E-mail',
      phone: 'Telefono',
      address: 'Indirizzo',
      street: 'Via',
      postalCode: 'Codice postale',
      city: 'Città',
      canton: 'Cantone',
      country: 'Paese',
      birthDate: 'Data di nascita',
      password: 'Password',
      confirmPassword: 'Conferma password',
      termsAndConditions: 'Accettare i termini e condizioni',
      privacyPolicy: 'Accettare la privacy policy',
    },
  },
  validation: {
    'de-CH': {
      required: 'Dieses Feld ist erforderlich',
      invalidEmail: 'Ungültige E-Mail-Adresse',
      invalidPhone: 'Ungültige Telefonnummer',
      invalidPostalCode: 'Ungültige Postleitzahl (4 Ziffern erforderlich)',
      passwordMismatch: 'Passwörter stimmen nicht überein',
      minLength: 'Mindestens {min} Zeichen erforderlich',
      maxLength: 'Maximal {max} Zeichen erlaubt',
      invalidDate: 'Ungültiges Datum',
      futureDate: 'Datum darf nicht in der Zukunft liegen',
      pastDate: 'Datum darf nicht in der Vergangenheit liegen',
    },
    'fr-CH': {
      required: 'Ce champ est obligatoire',
      invalidEmail: 'Adresse e-mail invalide',
      invalidPhone: 'Numéro de téléphone invalide',
      invalidPostalCode: 'Code postal invalide (4 chiffres requis)',
      passwordMismatch: 'Les mots de passe ne correspondent pas',
      minLength: 'Au moins {min} caractères requis',
      maxLength: 'Maximum {max} caractères autorisés',
      invalidDate: 'Date invalide',
      futureDate: 'La date ne peut pas être dans le futur',
      pastDate: 'La date ne peut pas être dans le passé',
    },
    'it-CH': {
      required: 'Questo campo è obbligatorio',
      invalidEmail: 'Indirizzo e-mail non valido',
      invalidPhone: 'Numero di telefono non valido',
      invalidPostalCode: 'Codice postale non valido (4 cifre richieste)',
      passwordMismatch: 'Le password non corrispondono',
      minLength: 'Almeno {min} caratteri richiesti',
      maxLength: 'Massimo {max} caratteri consentiti',
      invalidDate: 'Data non valida',
      futureDate: 'La data non può essere nel futuro',
      pastDate: 'La data non può essere nel passato',
    },
  },
  theme: {
    'de-CH': {
      light: 'Heller Modus',
      dark: 'Dunkler Modus',
      system: 'System',
    },
    'fr-CH': {
      light: 'Mode clair',
      dark: 'Mode sombre',
      system: 'Système',
    },
    'it-CH': {
      light: 'Modalità chiara',
      dark: 'Modalità scura',
      system: 'Sistema',
    },
  },
} as const;

// Date and number formatting configurations
export const FORMATTING_CONFIG = {
  'de-CH': {
    currency: {
      currency: 'CHF',
      locale: 'de-CH',
      style: 'currency',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    date: {
      locale: 'de-CH',
      dateStyle: 'medium' as const,
      timeStyle: 'short' as const,
    },
    number: {
      locale: 'de-CH',
    },
  },
  'fr-CH': {
    currency: {
      currency: 'CHF',
      locale: 'fr-CH',
      style: 'currency',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    date: {
      locale: 'fr-CH',
      dateStyle: 'medium' as const,
      timeStyle: 'short' as const,
    },
    number: {
      locale: 'fr-CH',
    },
  },
  'it-CH': {
    currency: {
      currency: 'CHF',
      locale: 'it-CH',
      style: 'currency',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    date: {
      locale: 'it-CH',
      dateStyle: 'medium' as const,
      timeStyle: 'short' as const,
    },
    number: {
      locale: 'it-CH',
    },
  },
} as const;

// Swiss postal code validation
export const POSTAL_CODE_PATTERN = /^\d{4}$/;

// Swiss phone number patterns
export const PHONE_PATTERNS = {
  mobile: /^(\+41|0041|0)\s?7[56789]\s?\d{3}\s?\d{2}\s?\d{2}$/,
  landline: /^(\+41|0041|0)\s?[2-6]\d\s?\d{3}\s?\d{2}\s?\d{2}$/,
  any: /^(\+41|0041|0)\s?[2-9]\d\s?\d{3}\s?\d{2}\s?\d{2}$/,
};

// Swiss license plate pattern
export const LICENSE_PLATE_PATTERN = /^[A-Z]{2}\s?\d{1,6}$/;
