name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
assignees:
  - SolombrinoIsmail

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Other approaches that might work...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking work)
        - High (Very important)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of the application does this relate to?
      options:
        - Customer Management
        - Vehicle Management
        - Contract Management
        - Payment Processing
        - Reporting
        - UI/UX
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: If applicable, write a user story for this feature
      placeholder: |
        As a [type of user]
        I want to [perform action]
        So that [achieve goal]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the success criteria for this feature?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add any mockups, wireframes, or examples
      placeholder: Drag and drop images here or provide links

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: Any additional information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with the project goals
          required: true
        - label: I have provided clear acceptance criteria
          required: true
