name: Preview Deployment Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  deployments: write

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Mark preview deployments inactive
        uses: actions/github-script@v7
        with:
          script: |
            const { data: deployments } = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment: 'preview',
              ref: context.payload.pull_request.head.sha
            });
            for (const d of deployments) {
              await github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: d.id,
                state: 'inactive',
                description: 'Preview cleaned up after PR close'
              });
            }
